# Generated by Django 6.0 on 2026-01-06 02:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=64)),
                ("display_name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stations",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "algorithm_version",
                    models.CharField(default="engine_v1", max_length=50),
                ),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_runs",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeStationSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("level", models.PositiveSmallIntegerField(default=1)),
                ("can_lead", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="station_skills",
                        to="core.employee",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_skills",
                        to="core.station",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="core.tenant",
            ),
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("shift_code", models.CharField(max_length=16)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="core.employee",
                    ),
                ),
                (
                    "schedule_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.schedulerun",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="core.station",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="station",
            index=models.Index(
                fields=["tenant", "code"], name="core_statio_tenant__b0043f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="station",
            index=models.Index(
                fields=["tenant", "is_active"], name="core_statio_tenant__69fa46_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="station",
            unique_together={("tenant", "code")},
        ),
        migrations.AddIndex(
            model_name="schedulerun",
            index=models.Index(
                fields=["tenant", "start_date"], name="core_schedu_tenant__4f22be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schedulerun",
            index=models.Index(
                fields=["tenant", "end_date"], name="core_schedu_tenant__30cae9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeestationskill",
            index=models.Index(
                fields=["tenant", "station"], name="core_employ_tenant__9cc131_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeestationskill",
            index=models.Index(
                fields=["tenant", "employee"], name="core_employ_tenant__c36453_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employeestationskill",
            unique_together={("tenant", "employee", "station")},
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["tenant", "name"], name="core_employ_tenant__f0a0f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["tenant", "is_active"], name="core_employ_tenant__e22105_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together={("tenant", "name")},
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["tenant", "date"], name="core_assign_tenant__408405_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["tenant", "station", "date"],
                name="core_assign_tenant__bae30e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assignment",
            unique_together={("tenant", "date", "station")},
        ),
    ]
