# Generated by Django 6.0 on 2026-01-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_assignable",
            field=models.BooleanField(default=True),
        ),
    ]
