# Generated by Django 6.0 on 2026-01-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_employee_is_assignable"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[("chef", "Chef"), ("staff", "Staff")],
                default="staff",
                max_length=20,
            ),
        ),
    ]
