# Generated by Django 6.0 on 2026-01-11 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_employee_role"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="assignment",
            name="core_assign_tenant__408405_idx",
        ),
        migrations.RemoveIndex(
            model_name="assignment",
            name="core_assign_tenant__bae30e_idx",
        ),
        migrations.AlterUniqueTogether(
            name="assignment",
            unique_together=set(),
        ),
    ]
