# Generated by Django 6.0 on 2026-01-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_assignment_core_assign_tenant__408405_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["tenant", "date"], name="core_assign_tenant__408405_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["tenant", "station", "date"],
                name="core_assign_tenant__bae30e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.UniqueConstraint(
                fields=("tenant", "date", "station", "employee"),
                name="uniq_assignment_per_employee_station_day",
            ),
        ),
    ]
