# Generated by Django 6.0 on 2026-04-02 04:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_assignment_core_assign_tenant__408405_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=16)),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "legend_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("paid_hours", models.FloatField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_definitions",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "code"], name="core_shiftd_tenant__cf5c60_idx"
                    )
                ],
                "unique_together": {("tenant", "code")},
            },
        ),
    ]
