# Generated by Django 6.0 on 2026-04-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_shiftdefinition"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="assignment",
            name="uniq_assignment_per_employee_station_day",
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.UniqueConstraint(
                fields=("schedule_run", "date", "station", "employee"),
                name="uniq_assignment_per_run_employee_station_day",
            ),
        ),
    ]
