# Generated by Django 6.0 on 2026-04-09 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_assignment_run_scoped_uniqueness"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyWorkspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year_month", models.CharField(max_length=7)),
                ("language", models.CharField(default="ja", max_length=8)),
                ("leave_requests", models.JSONField(blank=True, default=dict)),
                ("working_state", models.JSONField(blank=True, default=dict)),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="monthly_workspaces",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant", "year_month"], name="core_monthl_tenant__a3092f_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "year_month"),
                        name="uniq_monthly_workspace_per_tenant_month",
                    )
                ],
            },
        ),
    ]
